#!/usr/bin/env python3
"""Render the CPC appendix fair-campaign table from the committed JSON.

Does not run the bench. Numbers come only from
``examples/benchmarks/ase_fair_campaign_1.json``. The default ladder and
fixture are the freeze contract; this script refuses any other settings.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
JSON_PATH = ROOT / "examples" / "benchmarks" / "ase_fair_campaign_1.json"
MD_PATH = ROOT / "examples" / "benchmarks" / "fair_db_vs_ase_table.md"
TEX_PATH = (
    ROOT / "paper" / "cpc" / "src" / "figures" / "generated" / "fair_campaign_table.tex"
)

HEADER = (
    "% Auto-generated by paper/cpc/scripts/gen_appendix.py -- do not edit by hand.\n"
)

# Frozen campaign settings. Do not invent a cheaper ladder or fixture.
FROZEN_LADDER = [10, 50, 100, 200, 500]
FROZEN_FIXTURE_SUFFIX = "tiny_cuh2.con"


def _load() -> dict:
    payload = json.loads(JSON_PATH.read_text())
    ladder = list(payload.get("ladder") or [])
    fixture = str(payload.get("fixture") or "")
    if not payload.get("fair"):
        raise SystemExit(f"{JSON_PATH}: freeze requires fair=true")
    if not payload.get("cpc_appendix_freeze"):
        raise SystemExit(f"{JSON_PATH}: freeze requires cpc_appendix_freeze=true")
    if ladder != FROZEN_LADDER:
        raise SystemExit(
            f"{JSON_PATH}: ladder {ladder} is not the freeze {FROZEN_LADDER}"
        )
    if not fixture.endswith(FROZEN_FIXTURE_SUFFIX):
        raise SystemExit(
            f"{JSON_PATH}: fixture {fixture!r} is not {FROZEN_FIXTURE_SUFFIX}"
        )
    return payload


def render_markdown(payload: dict) -> str:
    lines = [
        "# Fair ASE.db vs readcon-db (same CON ladder)",
        "",
        f"Fixture: `{payload['fixture']}`  Ladder: {payload['ladder']}",
        "",
        "| N | rdb ins/s | ase ins/s | rdb ext/s | ase ext/s | rdb sel Cu (s) | ase sel Cu (s) | rdb8 (s) | ase8 (s) | Cu hits agree |",
        "|---|-----------|-----------|-----------|-----------|----------------|----------------|----------|----------|---------------|",
    ]
    by_n_rdb = {r["n_frames"]: r for r in payload["readcon_db"]}
    by_n_ase = {r["n_frames"]: r for r in payload["ase_db"]}
    par = {r["n_frames"]: r for r in payload["select_parity"]}
    for n in payload["ladder"]:
        r, a, p = by_n_rdb[n], by_n_ase[n], par[n]
        lines.append(
            "| {n} | {ri:.2e} | {ai:.2e} | {re:.2e} | {ae:.2e} | {rsc:.2e} | {asc:.2e} | {r8:.3f} | {a8:.3f} | {ag} |".format(
                n=n,
                ri=r["insert_frames_per_s"] or 0,
                ai=a["insert_frames_per_s"] or 0,
                re=r["extract_frames_per_s"] or 0,
                ae=a["extract_frames_per_s"] or 0,
                rsc=r["select_cu_mean_s"],
                asc=a["select_cu_mean_s"],
                r8=r["concurrent_8readers_extract_s"],
                a8=a["concurrent_8readers_extract_s"],
                ag="yes"
                if p["symbol_Cu_agree"]
                and p["natoms_agree"]
                and p.get("mass_agree", True)
                and p.get("volume_agree", True)
                else "NO",
            )
        )
    lines.append("")
    lines.append("Interchange (parse multi-frame CON):")
    lines.append("```json")
    lines.append(json.dumps(payload.get("interchange"), indent=2))
    lines.append("```")
    lines.append("")
    lines.append(
        "Legacy `bench_ase_db.py` Cu2 stand-in timings remain **unequal-workload** artifacts; this file is the fair campaign."
    )
    return "\n".join(lines) + "\n"


def _sci(v: float) -> str:
    mant, exp = f"{v:.2e}".split("e")
    return rf"{mant}\times 10^{{{int(exp)}}}"


def render_tex(payload: dict) -> str:
    by_n_rdb = {r["n_frames"]: r for r in payload["readcon_db"]}
    by_n_ase = {r["n_frames"]: r for r in payload["ase_db"]}
    par = {r["n_frames"]: r for r in payload["select_parity"]}
    rows = []
    for n in payload["ladder"]:
        r, a, p = by_n_rdb[n], by_n_ase[n], par[n]
        agree = (
            p["symbol_Cu_agree"]
            and p["natoms_agree"]
            and p.get("mass_agree", True)
            and p.get("volume_agree", True)
        )
        rows.append(
            rf"{n} & ${_sci(r['insert_frames_per_s'] or 0)}$ & ${_sci(a['insert_frames_per_s'] or 0)}$"
            rf" & ${_sci(r['extract_frames_per_s'] or 0)}$ & ${_sci(a['extract_frames_per_s'] or 0)}$"
            rf" & ${_sci(r['select_cu_mean_s'])}$ & ${_sci(a['select_cu_mean_s'])}$"
            rf" & ${r['concurrent_8readers_extract_s']:.3f}$ & ${a['concurrent_8readers_extract_s']:.3f}$"
            rf" & {'yes' if agree else 'no'} \\"
        )
    ix = payload.get("interchange") or {}
    ix_note = ""
    if ix:
        ix_note = (
            rf" Interchange parse of $100$ frames:"
            rf" readcon ${ix['readcon_frames_per_s']:.0f}\,\mathrm{{s}}^{{-1}}$,"
            rf" \texttt{{ase.io.read}} ${ix['ase_io_frames_per_s']:.0f}\,\mathrm{{s}}^{{-1}}$"
            rf" ({ix['repeats']} repeats)."
        )
    body = [
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{Fair ASE.\texttt{db} vs readcon-db on the same CON ladder",
        r"(\texttt{resources/test/tiny\_cuh2.con},",
        r"$N\in\{10,50,100,200,500\}$). Insert and extract are frames per",
        r"second. Select is mean wall time for symbol \texttt{Cu}. Eight-reader",
        r"extract is wall seconds. Hit counts for Cu, natoms, mass, and volume",
        r"agree. Source:",
        r"\texttt{examples/benchmarks/ase\_fair\_campaign\_1.json}.",
        r"This appendix is a campaign-store measurement; it is not the main",
        r"CPC claim (readcon-core).",
        ix_note.strip(),
        r"}",
        r"\label{tab:fair-campaign}",
        r"\begin{tabular}{@{}rrrrrrrrrl@{}}",
        r"\toprule",
        r"$N$ & rdb ins/s & ase ins/s & rdb ext/s & ase ext/s &",
        r"rdb sel Cu (s) & ase sel Cu (s) & rdb8 (s) & ase8 (s) & agree \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    return HEADER + "\n".join(body)


def _diff(path: Path, got: str) -> str | None:
    want = path.read_text() if path.is_file() else ""
    if want == got:
        return None
    return f"{path}: generated text does not match the committed freeze"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="require committed markdown and TeX to match the JSON freeze",
    )
    args = ap.parse_args()
    payload = _load()
    md = render_markdown(payload)
    tex = render_tex(payload)
    if args.check:
        errors = [e for e in (_diff(MD_PATH, md), _diff(TEX_PATH, tex)) if e]
        if errors:
            for e in errors:
                print(e, file=sys.stderr)
            return 1
        print(f"ok freeze {JSON_PATH.relative_to(ROOT)}")
        return 0
    TEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    TEX_PATH.write_text(tex)
    if MD_PATH.read_text() != md:
        raise SystemExit(f"{MD_PATH}: committed markdown drifted from {JSON_PATH}")
    print(f"wrote {TEX_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
